# Concrete pen tool configuration (finetip pigment 0.3mm)
# Extends pen_tool.v1 schema

schema: pen_tool.v1
name: "finetip_pigment_0.3mm"

# Physical parameters
tip_diameter_mm: 0.30
overlap_frac: 0.25
max_passes: 4

# Motion parameters
feed_mm_s: 120.0
travel_mm_s: 250.0
safe_z_mm: 5.0
draw_z_mm: -0.2
plunge_mm_s: 10.0

# Tool offset (calibrate via cross+dot test)
offset_mm: [12.50, -6.20, 0.00]

# G-code macros
macros:
  pen_up: "PEN_UP.gcode"
  pen_down: "PEN_DOWN.gcode"

# Motion control
accel:
  xy_mm_s2: 1500.0

# Path style
joins:
  cap_style: "round"
  join_style: "round"

