# Job schema v1
# Purpose: Complete job manifest for inference
# Used by: scripts/paint.py, src/utils/gcode_generator.py

schema: job.v1
semver: "1.0.0"

# Required fields
required:
  - machine_profile
  - inputs
  - limits
  - passes
  - artifacts

# Field definitions
fields:
  machine_profile:
    type: "str"
    description: "Machine profile identifier (e.g., grbl_airbrush.v1)"
  inputs:
    type: "dict"
    required:
      - target_image_path
      - pen_layer_path
  limits:
    type: "dict"
    required:
      - max_strokes
      - bbox_mm
  passes:
    type: "list"
    description: "Ordered list of painting passes"
    items:
      - name: "str"              # "cmy" or "pen"
        strokes_path: "str"      # Path to strokes YAML
  artifacts:
    type: "dict"
    required:
      - cmy_gcode_out
      - pen_gcode_out
      - manifest_out

# Example (for reference)
example:
  schema: "job.v1"
  machine_profile: "grbl_airbrush.v1"
  inputs:
    target_image_path: "data/target_images/cmy_only/hard/sample_hd.png"
    pen_layer_path: "data/target_images/pen_layers/hard/sample_hd.yaml"
  limits:
    max_strokes: 1500
    bbox_mm:
      x: [0, 210]
      y: [0, 297]
      z: [0, 30]
  passes:
    - name: "cmy"
      strokes_path: "outputs/strokes/sample_hd_strokes.yaml"
    - name: "pen"
      vectors_path: "outputs/pen/sample_hd_pen.yaml"
  artifacts:
    cmy_gcode_out: "gcode_output/sample/painting_cmy.gcode"
    pen_gcode_out: "gcode_output/sample/painting_pen.gcode"
    manifest_out: "gcode_output/sample/painting_manifest.yaml"

