# LUT schema v1
# Purpose: Metadata for lookup table tensors
# Used by: src/airbrush_simulator/differentiable_renderer.py

schema: luts.v1
semver: "1.0.0"

# Color LUT (CMY → linear RGB)
color_lut:
  grid:
    c: 11                        # Number of C samples
    m: 11                        # Number of M samples
    y: 11                        # Number of Y samples
  domain: [0.0, 1.0]             # CMY input range
  shape: [11, 11, 11, 3]         # [Nc x Nm x Ny x 3]
  dtype: "float32"
  values_path: "configs/sim/luts/color_lut.pt"
  description: "Trilinear interpolation on CMY cube → linear RGB [0,1]"

# Alpha LUT (Z, speed → coverage factor)
alpha_lut:
  axes:
    z: [5, 10, 15, 20, 25]       # mm
    v: [50, 100, 150, 200, 250]  # mm/s
  shape: [5, 5]                  # [Nz x Nv]
  dtype: "float32"
  values_path: "configs/sim/luts/alpha_lut.pt"
  description: "Bilinear interpolation on Z×V grid → coverage [0,1]"

# PSF LUT (Z, speed → point spread function)
psf_lut:
  axes:
    z: [5, 10, 15, 20, 25]       # mm
    v: [50, 100, 150, 200, 250]  # mm/s
  kernel_size: 15                # K×K kernel (must be odd)
  shape: [5, 5, 15, 15]          # [Nz x Nv x K x K]
  dtype: "float32"
  values_path: "configs/sim/luts/psf_lut.pt"
  description: "Bilinear interpolation on Z×V grid → normalized Gaussian kernel"

# Metadata
metadata:
  machine_profile: "grbl_airbrush.v1"
  calibration_date: "2025-10-27"
  operator: "Operator Name"

