# Machine schema v1
# Purpose: Machine profile structure and validation
# Used by: src/utils/validators, src/utils/gcode_generator.py

schema: machine.v1
semver: "1.0.0"

# Required fields
required:
  - work_area_mm
  - canvas_mm
  - gcode_flavor
  - units
  - feed_units
  - feeds
  - acceleration
  - macros
  - safety

# Field definitions
fields:
  work_area_mm:
    type: "dict"
    required: [x, y, z]
    units: "mm"
    description: "Machine physical travel limits (origin at 0,0)"
  canvas_mm:
    type: "dict"
    required: [x_min, x_max, y_min, y_max]
    units: "mm"
    description: "Painting surface bounds within machine work area (can be offset from origin)"
  gcode_flavor:
    type: "str"
    allowed: ["grbl_1.1f", "marlin_2.0", "reprap"]
  units:
    type: "str"
    allowed: ["mm", "inch"]
  feed_units:
    type: "str"
    allowed: ["mm/min", "mm/s"]
  feeds:
    type: "dict"
    required: [max_xy_mm_s, max_z_mm_s, rapid_mm_s]
    description: "Feed rate limits (mm/s)"
  acceleration:
    type: "dict"
    required: [max_xy_mm_s2, max_z_mm_s2]
    units: "mm/s²"
    description: "Acceleration limits"
  macros:
    type: "dict"
    required: [include_dir, purge, pen_up, pen_down]
  safety:
    type: "dict"
    required: [soft_limits, purge_zone_mm]

# Validators
validators:
  - "work_area_mm.x > 0"
  - "work_area_mm.y > 0"
  - "work_area_mm.z > 0"
  - "canvas_mm.x_min >= 0"
  - "canvas_mm.x_max <= work_area_mm.x"
  - "canvas_mm.y_min >= 0"
  - "canvas_mm.y_max <= work_area_mm.y"
  - "canvas_mm.x_max > canvas_mm.x_min"
  - "canvas_mm.y_max > canvas_mm.y_min"
  - "feeds.max_xy_mm_s > 0"
  - "feeds.max_z_mm_s > 0"
  - "feeds.rapid_mm_s > 0"
  - "acceleration.max_xy_mm_s2 > 0"
  - "acceleration.max_z_mm_s2 > 0"
  - "macros.include_dir exists"

