# Pen tracer schema v1
# Purpose: Black layer extraction and path generation configuration
# Used by: pen_tracer.py, validators.py

schema: pen_tracer.v1
semver: "1.0.0"

# LAB thresholds for black ink extraction
thresholds:
  lab_l_max: 18.0                     # Max L* for "black" (lower = darker)
  a_abs_min: 0.0                      # Min |a*| chroma gate (0 = no gate)
  b_abs_min: 0.0                      # Min |b*| chroma gate (0 = no gate)

# Morphological operations on binary mask
morphology:
  close_px: 1                         # Morphological close kernel size (pixels)
  open_px: 0                          # Morphological open kernel size (pixels)
  min_area_px: 16                     # Discard components smaller than this (pixels)

# Vectorization parameters
vectorization:
  simplify_tol_px: 1.2                # Douglas-Peucker tolerance (pixels)
  potrace_turdsize: 2                 # Potrace speckle filter (pixels)

# Component classification
classification:
  line_like_width_px: 6               # Width threshold: below → "line", above → "region"
  donut_hole_min_area_px: 36          # Keep inner holes larger than this (pixels)

# Region filling strategy
filling:
  hatch_angles_deg: [0]               # Hatch angles for successive passes (degrees)
  hatch_spacing_scale: 1.00           # Scale factor for hatch spacing (dimensionless)
  
  # Overshading: map L* to extra passes (darker → more passes)
  darkness_to_passes:
    - { l_max: 14.0, passes: 3 }      # Very dark: 3 extra passes (4 total)
    - { l_max: 16.0, passes: 2 }      # Dark: 2 extra passes (3 total)
    - { l_max: 18.0, passes: 1 }      # Medium: 1 extra pass (2 total)

# Contour packing parameters (for line-like components)
contours:
  endcap_extra_len_mm: 0.3            # Extend line ends for coverage (mm)
  max_shells_per_side: 12             # Safety limit on offset contours

# Visibility and quality gates
visibility:
  min_coverage: 0.0005                # Min black coverage fraction to keep layer
  max_gap_frac: 0.02                  # Max allowed white gap fraction in regions (CI gate)

# Debug output
debug:
  save_intermediates: true            # Save masks, distance transform, paths to debug/

# Bounds (enforced by validator)
bounds:
  lab_l_max: [0.0, 50.0]
  simplify_tol_px: [0.1, 5.0]
  line_like_width_px: [1, 50]
  hatch_angles_deg: [-180.0, 180.0]
  hatch_spacing_scale: [0.5, 2.0]
  endcap_extra_len_mm: [0.0, 5.0]
  max_shells_per_side: [1, 50]
  min_coverage: [0.0, 1.0]
  max_gap_frac: [0.0, 0.5]

