# Pen vectors schema v1
# Purpose: Serialization format for pen layer instructions
# Used by: pen_tracer.py, gcode_generator.py, validators.py, GUI

schema: pen_vectors.v1
semver: "1.0.0"

# Image/rendering context
render_px: [1280, 908]                # [W, H] rendering resolution
work_area_mm: [210.0, 297.0]          # Canvas dimensions in mm

# Path list (each path is a polyline in image frame mm)
paths:
  - id: "pen-000001"
    kind: "polyline"                  # "polyline" | "polygon"
    role: "outline"                   # "outline" | "hatch" | "fill"
    tip_diameter_mm: 0.30
    z_mm: -0.2
    feed_mm_s: 120.0
    points_mm:                        # Image-frame millimeters (top-left, +Y down)
      - [x1_mm, y1_mm]
      - [x2_mm, y2_mm]
      # ... more points

# Metadata (provenance)
metadata:
  tool_name: "finetip_pigment_0.3mm"
  offset_mm: [12.50, -6.20, 0.00]    # Tool offset from airbrush origin
  hatch_angles_deg: [0, 90, 45, 135] # Angles used in hatching
  generated_at: "2025-10-31T12:00:00Z"
  tracer_version: "pen_tracer.v2"

# Bounds (enforced by validator)
bounds:
  tip_diameter_mm: [0.1, 2.0]
  z_mm: [-2.0, 10.0]
  feed_mm_s: [10.0, 300.0]
  points_mm:
    x: [0.0, 210.0]                   # A4 width
    y: [0.0, 297.0]                   # A4 height

# Fields (path structure)
fields:
  id:
    type: "str"
    description: "Unique path identifier"
  kind:
    type: "str"
    enum: ["polyline", "polygon"]
    description: "Path topology"
  role:
    type: "str"
    enum: ["outline", "hatch", "fill"]
    description: "Path semantic role"
  tip_diameter_mm:
    type: "float"
    description: "Pen tip diameter (mm)"
  z_mm:
    type: "float"
    description: "Pen Z position (mm)"
  feed_mm_s:
    type: "float"
    description: "XY feed rate (mm/s)"
  points_mm:
    type: "list[list[float, float]]"
    description: "Polyline points in image-frame mm"

