# Stroke schema v1
# Purpose: Single source of truth for stroke parameter ranges and structure
# Used by: All modules (validators, env, renderer, gcode_gen)

schema: stroke.v1
semver: "1.0.0"

# Units
units:
  xy: "mm"
  z: "mm"
  speed: "mm/s"

# Bounds (valid ranges)
bounds:
  x: [0.0, 210.0]                # A4 width
  y: [0.0, 297.0]                # A4 height
  z: [0.0, 30.0]                 # Nozzle height
  speed: [1.0, 300.0]            # Plotter speed

# Fields (stroke structure)
fields:
  id:
    type: "str"
    description: "Unique stroke identifier (epoch-idx-uuid)"
  bezier:
    type: "dict"
    description: "Cubic Bézier control points (4 points, xy in mm)"
    required:
      - p1: [float, float]
      - p2: [float, float]
      - p3: [float, float]
      - p4: [float, float]
  z_profile:
    type: "dict"
    description: "Nozzle height at start and end (mm)"
    required:
      - z0: float
      - z1: float
  speed_profile:
    type: "dict"
    description: "Speed at start and end (mm/s)"
    required:
      - v0: float
      - v1: float
  color_cmy:
    type: "dict"
    description: "CMY color (0.0-1.0)"
    required:
      - c: float
      - m: float
      - y: float
    range: [0.0, 1.0]

# Validators (enforced by src.utils.validators)
validators:
  - "all control points within bounds.xy"
  - "z0, z1 within bounds.z"
  - "v0, v1 within bounds.speed"
  - "0.0 <= c, m, y <= 1.0"

# Action vector format (15-D, normalized [-1,1] in env)
action_vector:
  dims: 15
  layout: [x1, y1, x2, y2, x3, y3, x4, y4, z0, z1, v0, v1, c, m, y]

