# Scanner profile v1
# Used by: src/data_pipeline/calibrate.py
# Purpose: Scan ingestion settings for calibration workflow

schema: scanner.v1

# Input settings
input:
  color_space: "srgb"            # Scanner output color space
  linearize: true                # Convert sRGB → linear RGB for measurements

# Scan corrections
corrections:
  deskew: true                   # Correct rotation
  homography:
    enabled: true                # Perspective correction using fiducials

# Patch sampling (for color measurements)
patch_sampling:
  method: "median"               # "median", "mean", or "center"
  roi_margin_px: 6               # Shrink ROI by N pixels to avoid edges

# DPI (recorded manually per scan session)
dpi:
  default: 600                   # Dots per inch (updated per scan)
  x: 600
  y: 600

