# Manual calibration measurements
# Purpose: Operator-entered measurements from printed calibration patterns
# Instructions: Measure in calibrated image editor (linear RGB, mm ruler)
# Used by: src/data_pipeline/calibrate.py (build_luts_from_manual)

schema: manual_calibration_results.v1

# Scanner DPI (record from scan session)
scanner_dpi: 600

# Color measurements (label → measured RGB)
# Label format: Cxyz where x,y,z are CMY indices (0-4 for 5 steps)
color_measurements:
  C000:
    cmy_input: [0.0, 0.0, 0.0]
    rgb_linear_measured: [1.0, 1.0, 1.0]  # White paper
  # ... (operator fills in 125 entries)
  # C111:
  #   cmy_input: [0.25, 0.25, 0.25]
  #   rgb_linear_measured: [0.xx, 0.xx, 0.xx]

# PSF and alpha measurements (label → measured properties)
# Label format: Pxy where x is Z index, y is speed index
psf_alpha_measurements:
  P00:
    z_mm: 5.0
    speed_mm_s: 50.0
    alpha_measured: 0.xx         # Coverage factor vs. paper white
    width_mm: x.x                # Dot diameter/characteristic size
    shape_description: "circular"
  # ... (operator fills in 25 entries)

# Layering measurements (overlap validation)
# Label format: Lxy
layering_measurements:
  L00:
    base_cmy: [1.0, 0.0, 0.0]
    top_cmy: [0.0, 1.0, 0.0]
    base_rgb_linear_measured: [0.xx, 0.xx, 0.xx]
    top_rgb_linear_measured: [0.xx, 0.xx, 0.xx]
    overlap_rgb_linear_measured: [0.xx, 0.xx, 0.xx]
  # ... (operator fills in 9 entries)

# Metadata
calibration_date: "YYYY-MM-DD"
operator: "Operator Name"
notes: "Any observations or issues during printing/measurement"

