# Concrete pen tracer configuration
# Extends pen_tracer.v1 schema

schema: pen_tracer.v1

# LAB thresholds for black extraction
thresholds:
  lab_l_max: 18.0
  a_abs_min: 0.0
  b_abs_min: 0.0

# Morphology
morphology:
  close_px: 1
  open_px: 0
  min_area_px: 16

# Vectorization
vectorization:
  simplify_tol_px: 1.2
  potrace_turdsize: 2

# Classification
classification:
  line_like_width_px: 6
  donut_hole_min_area_px: 36

# Filling
filling:
  hatch_angles_deg: [0]
  hatch_spacing_scale: 1.00
  darkness_to_passes:
    - { l_max: 14.0, passes: 3 }
    - { l_max: 16.0, passes: 2 }
    - { l_max: 18.0, passes: 1 }

# Contours
contours:
  endcap_extra_len_mm: 0.3
  max_shells_per_side: 12

# Visibility gates
visibility:
  min_coverage: 0.0005
  max_gap_frac: 0.02

# Debug
debug:
  save_intermediates: true

