# Pen Tracer V2 Configuration
# ============================================================================
# This config controls how pen outlines and hatching are generated to
# complement CMY airbrush painting. The pen adds:
#   1. Sharp outlines at hard color boundaries (edge_detection)
#   2. Hatching for colors/darkness the CMY palette cannot reproduce (shadow_hatching)
#
# See documentation/PEN_TRACER_PARAMS.md for detailed parameter guide
# ============================================================================

schema: pen_tracer.v2

# ============================================================================
# OUTPUT RESOLUTION
# ============================================================================
output:
  # Target output height in pixels. Width is calculated to maintain aspect ratio.
  # 
  # COMMON VALUES:
  #   - 3508: A4 height at 300 DPI (210×297mm) - professional print quality
  #   - 2339: A4 height at 200 DPI - good quality, faster processing
  #   - 1754: A4 height at 150 DPI - draft quality
  #   - null: use render_px from environment config (for simulation testing)
  # 
  # EFFECT: Higher = sharper details, more paths, longer processing time
  target_height_px: 3508
  
  # Safety bounds (clamping limits)
  min_px: 512    # Minimum dimension (protects against invalid configs)
  max_px: 4096   # Maximum dimension (prevents OOM)

# ============================================================================
# EDGE DETECTION (Outline Extraction)
# ============================================================================
edge_detection:
  enabled: true  # Set false to disable outline generation
  
  # Canny edge detection thresholds (applied to luminance channel)
  # Controls which color transitions are detected as "edges"
  # 
  # TUNING GUIDE:
  #   Higher thresholds → Only HARD color changes (e.g., dark blue vs white)
  #   Lower thresholds → Also detect SOFT changes (e.g., blue vs light blue)
  # 
  # RECOMMENDED RANGES:
  #   canny_low:  50-150  (lower = more edges, including soft gradients)
  #   canny_high: 100-300 (higher = only sharp transitions)
  #   Typical ratio: canny_high = 2-3× canny_low
  # 
  # EXAMPLES:
  #   - (50, 150):   Captures soft gradients, good for watercolor-style images
  #   - (100, 200):  Balanced - only moderately sharp edges (current setting)
  #   - (150, 300):  Very selective - only dramatic color jumps
  # 
  # EFFECT: Higher → fewer, cleaner outlines; Lower → more detail, busier look
  canny_low: 100.0
  canny_high: 200.0
  
  # Edge filtering
  # 
  # min_length_px: Discard edges shorter than this (removes noise/texture)
  #   RANGE: 5-50 pixels
  #   - 5-10:  Keep fine details, more strokes
  #   - 20-30: Clean, essential outlines only (current)
  #   - 40+:   Very coarse, major features only
  min_length_px: 20
  
  # link_distance_px: Connect edges if gap is ≤ this (bridges broken contours)
  #   RANGE: 0-10 pixels
  #   - 0: No linking (fragmented)
  #   - 2-5: Moderate linking (current)
  #   - 8+: Aggressive linking (may join unrelated edges)
  link_distance_px: 2
  
  # simplify_tol_px: Douglas-Peucker simplification tolerance
  #   RANGE: 0.5-5.0 pixels
  #   - 0.5-1.0: High fidelity, more points, larger file
  #   - 1.5-2.5: Balanced (current)
  #   - 3.0+: Aggressive smoothing, angular look
  #   EFFECT: Higher → smoother curves, fewer points, smaller G-code
  simplify_tol_px: 1.5

# ============================================================================
# SHADOW HATCHING (Darkness Filling)
# ============================================================================
shadow_hatching:
  enabled: true  # Set false to disable hatching
  
  # Gamut-aware mode: only hatch regions the CMY airbrush CANNOT reproduce
  # When true, hatching is restricted to out-of-gamut colors
  # When false, hatching is applied to all dark regions (ignore gamut)
  # 
  # RECOMMENDED: true (prevents over-inking and double-tracing)
  gamut_aware: true
  
  # ──────────────────────────────────────────────────────────────────────────
  # CMY Airbrush Gamut Definition (fallback values)
  # ──────────────────────────────────────────────────────────────────────────
  # These define what colors your CMY airbrush CAN reproduce.
  # Pen hatching is only applied OUTSIDE this gamut.
  # 
  # NOTE: These values will be OVERRIDDEN by calibration data when available
  # (set calibration.calibration_file below to use measured gamut)
  # 
  cmy_gamut:
    # Darkest black achievable with CMY (L* in LAB color space)
    # Anything darker needs pen hatching for true black
    # 
    # TYPICAL VALUES:
    #   - 10-15: High-quality inkjet printer (rich blacks)
    #   - 15-25: Airbrush with good coverage (current)
    #   - 25-35: Light/translucent inks
    # 
    # EFFECT: Higher → more hatching (assumes CMY can't go very dark)
    #         Lower → less hatching (assumes CMY achieves deep blacks)
    min_luminance: 15.0
    
    # Maximum chroma (color saturation) CMY can achieve
    # Highly saturated pure colors may exceed CMY gamut
    # 
    # TYPICAL VALUES:
    #   - 60-80: Standard CMY airbrush (current)
    #   - 80-100: High-saturation inks
    #   - 40-60: Muted/pastel palette
    # 
    # EFFECT: Lower → more hatching (narrower gamut)
    #         Higher → less hatching (wider gamut)
    max_chroma: 80.0
    
    # Hue ranges CMY can reproduce well (degrees, 0-360)
    # Use multiple ranges to exclude problematic hues
    # 
    # EXAMPLES:
    #   - [[0, 360]]:           All hues (no filtering) - current
    #   - [[0, 180]]:           Reds/yellows/greens only
    #   - [[0, 60], [120, 240]]: Exclude greenish-yellows and purples
    # 
    # NOTE: Most CMY systems struggle with pure blues and deep purples
    hue_ranges:
      - [0, 360]  # All hues (will be refined by calibration)
  
  # ──────────────────────────────────────────────────────────────────────────
  # Darkness Levels (Hatching Strategy)
  # ──────────────────────────────────────────────────────────────────────────
  # Define how different darkness ranges are hatched
  # Only applied to regions OUTSIDE CMY gamut
  # 
  # CRITICAL: Each level is EXCLUSIVE (l_min to l_max)
  # This prevents overlapping/double-tracing
  # 
  # L* (Luminance) Reference:
  #   0   = Pure black
  #   50  = Medium gray
  #   100 = Pure white
  # 
  # TUNING STRATEGY:
  #   - Darker regions (low L*): Denser hatching (more passes, closer lines)
  #   - Lighter regions (high L*): Sparse hatching (single pass, wider lines)
  #   - Add/remove levels to control granularity
  # 
  darkness_levels:
    # LEVEL 1: Very dark shadows (L* 0-30) - nearly black
    # Single-pass, 45° hatching
    - l_min: 0.0      # Include pure black
      l_max: 30.0     # Up to dark gray
      passes: 1       # Number of hatching passes (1-3 typical)
      hatch_angles: [45]  # Angles in degrees (single value = 1 direction)
      # 
      # TUNING:
      #   passes: 1 = sparse, 2 = denser, 3 = very dense (may over-ink)
      #   hatch_angles: [45] = single direction (current)
      #                 [45, 135] = cross-hatch (denser, slower)
      #                 [0, 60, 120] = triple hatch (very dense)
    
    # LEVEL 2: Dark shadows (L* 30-50)
    - l_min: 30.0
      l_max: 50.0
      passes: 1
      hatch_angles: [45]
    
    # LEVEL 3: Medium-dark shadows (L* 50-70)
    - l_min: 50.0
      l_max: 70.0
      passes: 1
      hatch_angles: [45]
    # 
    # TO EXTEND: Add more levels for finer gradation
    # Example: Add L* 70-85 for very light shadows
  
  # ──────────────────────────────────────────────────────────────────────────
  # Morphology & Filtering
  # ──────────────────────────────────────────────────────────────────────────
  # 
  # min_area_px: Discard shadow regions smaller than this (removes noise)
  #   RANGE: 100-2000 pixels
  #   - 100-300: Keep fine details, more hatching
  #   - 500-1000: Balanced (current)
  #   - 1500+: Only large shadow areas
  min_area_px: 500
  
  # ──────────────────────────────────────────────────────────────────────────
  # Hatching Pattern Density
  # ──────────────────────────────────────────────────────────────────────────
  # 
  # spacing_scale: Multiplier for hatch line spacing
  #   Base spacing = pen_width × spacing_scale
  #   RANGE: 1.5-5.0
  #   - 1.5-2.0: Dense hatching (darker appearance, more ink)
  #   - 2.5-3.0: Balanced (current) - lets CMY colors show through
  #   - 3.5-5.0: Very sparse (subtle hatching, minimal ink)
  # 
  # EFFECT: Higher → lighter hatching, more color visible, faster execution
  spacing_scale: 2.5
  
  # min_line_spacing_mm: Absolute minimum spacing between parallel hatch lines
  #   Safety limit to prevent over-inking
  #   RANGE: 0.3-1.0 mm
  #   - 0.3: Very dense (for fine pens)
  #   - 0.5: Balanced (current)
  #   - 0.8+: Sparse (for thick pens or fast execution)
  min_line_spacing_mm: 0.5
  
  # ──────────────────────────────────────────────────────────────────────────
  # Coverage Limits
  # ──────────────────────────────────────────────────────────────────────────
  # 
  # max_hatch_coverage: Maximum fraction of canvas covered by hatching (0.0-1.0)
  #   Prevents over-inking and ensures CMY colors dominate
  #   RANGE: 0.10-0.75
  #   - 0.10-0.20: Very sparse, pen as accent (current)
  #   - 0.30-0.50: Moderate, pen and color balanced
  #   - 0.60-0.75: Dense, pen-dominant illustration style
  # 
  # CRITICAL: This is a hard limit. Once reached, no more hatching is added.
  # Algorithm stops at darkest L* levels first, then progressively lighter.
  max_hatch_coverage: 0.20

# ============================================================================
# CALIBRATION INTEGRATION
# ============================================================================
calibration:
  # Path to measured CMY gamut data (YAML file from calibration pipeline)
  # When provided, overrides cmy_gamut fallback values above
  # 
  # SET TO: Path to your calibration file after running calibration tests
  # LEAVE null: To use fallback values (safe defaults)
  # 
  # Example: "outputs/calibration/cmy_gamut_measured.yaml"
  calibration_file: null
  
  # Gamut expansion margin (safety factor)
  # Expands the CMY gamut slightly to avoid harsh boundaries
  # 
  # RANGE: 0.0-0.15 (fraction)
  # - 0.00: No expansion (strict gamut)
  # - 0.05: 5% expansion (current, recommended)
  # - 0.10+: Conservative (more hatching, less reliance on CMY)
  # 
  # EFFECT: Higher → more hatching (assumes narrower CMY gamut)
  margin: 0.05

# ============================================================================
# DEBUG OUTPUT
# ============================================================================
debug:
  # Save intermediate processing artifacts for inspection
  # Useful for tuning parameters and diagnosing issues
  # 
  # EFFECT: When true, saves additional images to output directory
  #         Minimal performance impact (~5-10% slower)
  # 
  save_intermediates: true   # Save all debug artifacts
  save_gamut_mask: true      # Mask showing out-of-gamut regions (magenta overlay)
  save_edge_mask: true       # Binary edge detection result
  save_shadow_masks: true    # Shadow masks for each darkness level

