# CPU Reference Renderer Configuration (v1)
# Defines physical behavior for deterministic OpenCV-based airbrush simulation
#
# This config controls width, mass deposition, visibility gates, and profile shape.
# Calibration will overwrite these values based on real measurements.

schema: renderer_cpu.v1

# Rendering mode: "opencv_distance" (distance transform + radial profile) or "stamp_train" (textured stamps)
mode: "opencv_distance"

# Visibility thresholds (skip imperceptible strokes to save compute & avoid noise)
visibility:
  min_alpha_visible: 0.0125        # per-pixel α below this is zeroed
  min_delta_e_visible: 0.8         # minimum perceptual difference (ΔE2000)
  min_stroke_coverage: 0.0001      # fraction of canvas; strokes below this are skipped
  min_center_luminance_drop: 0.05  # center of stroke must darken by at least this much

# Width model: maps (z, v) → spray width in mm
width_model:
  # Z-dependent min/max width (mm). Much wider range for alcohol ink airbrush.
  z_knots_mm: [2.0, 4.0, 6.0, 8.0, 10.0, 15.0, 20.0]
  width_min_mm: [0.5, 0.8, 1.2, 1.8, 2.5, 4.0, 6.0]   # Increased range dramatically
  width_max_mm: [1.5, 2.5, 4.0, 6.0, 8.0, 12.0, 16.0]  # Much wider at higher Z
  
  # Speed scaling of width (multiplicative factor)
  v_knots_mm_s: [10.0, 30.0, 60.0, 120.0, 240.0]
  width_scale:   [1.30, 1.15, 1.00, 0.85, 0.70]  # Slightly more pronounced

# Radial opacity profile shape
profile:
  type: "flat_core_gaussian_skirt"
  core_frac: 0.40               # r_core = core_frac * (width/2)
  skirt_sigma_frac: 0.28        # σ_skirt = skirt_sigma_frac * (width/2)
  skirt_power: 1.8              # tail shaping exponent (higher = sharper falloff)
  margin_factor: 1.5            # ROI margin = margin_factor * (width/2)

# Deposition model: mass of "opacity" per unit length
deposition:
  # Mass per second vs Z (calibrated from dot tests)
  # NOTE: Reduced for alcohol ink transparency - allows layering to show through
  z_knots_mm: [2.0, 4.0, 6.0, 8.0, 10.0, 15.0, 20.0]
  mass_per_sec: [8.0, 7.0, 6.0, 5.0, 4.2, 3.2, 2.5]  # Much lower for transparency
  
  # Speed scaling: mass_per_mm = mass_per_sec / (v^speed_exponent)
  speed_exponent: 1.0           # default: inverse proportional to speed
  
  # Global amplitude scale (tuned via layering tests)
  k_mass: 2.8                   # Balanced for visible but transparent alcohol ink

# Stamp train mode (alternative to distance transform)
stamp_train:
  patterns: []                  # paths to nozzle pattern images
  unit_diam_mm: 1.0
  spacing_mm: 0.5
  jitter_mm: 0.08
  noise_gain: 0.12

# Color mixing/layering
mixing:
  mode: "layer_over"            # "layer_over" (alpha-over) or "kubelka_munk" (future)
  km_params_path: null

# Randomness control (for speckle/texture)
randomness:
  seed: 42
  speckle: true
  speckle_gain: 0.08
  speckle_scale: 2.0            # feature size in pixels

# Sampling along polyline
sampling:
  max_step_mm: 0.25             # maximum spacing between profile evaluations
  min_samples: 8                # minimum samples per stroke

